### ISSUE TITLE
strange commit file types?

### ISSUE THREAD

**Issue by javamonn** [ethanwilkins/anrcho#1]
You don't appear to be checking in actual code, github thinks it's a binary file and won't display it, I also can't clone the repo and open it in a standard text editor

**Comment by ethanwilkins** [comment]
Could you explain in more detail, like what files in particular?

**Comment by javamonn** [comment]
Apologies for not leaving a note here when I closed this. Stumbled across anrcho late one night, pulled things down locally, was left confused by binary dotfiles e.g. [._messages_controller.rb](https://github.com/ethanwilkins/anrcho/blob/master/app/controllers/._messages_controller.rb) that accompany the plain text ruby files. I closed the issue as soon as I realized these are likely used by an editor, plugin, etc - not the plain text files themselves. Apologies!

**Comment by ethanwilkins** [comment]
That's okay, thanks for the feedback. I'm pretty sure they're from working on OSX a while back. I've actually been trying to think of an easy way to get rid of them all as I'm working on linux now.

**Comment by marekjm** [comment]
What about 'find . -name '._*' | xargs rm -i' for *an easy way to get rid of them*?

**Comment by marekjm** [comment]
I am closing the issue as the [associated pull request](https://github.com/ethanwilkins/anrcho/pull/2) has been merged. If anything has escaped my attention, feel free to reopen.
