### ISSUE TITLE
IRC?

### ISSUE THREAD

**Issue by omouse** [ethanwilkins/anrcho#4]
The #anrcho channel is available on freenode; might be a good place to hang out and talk about Rails, Ruby, and Anrcho development.

**Comment by ethanwilkins** [comment]
Great idea, I should have the channel and something setup with cloud9 by tomorrow. I'll also be uploading some new features to the site as well.

**Comment by ethanwilkins** [comment]
Here are the cloud9 links, just finished setup:
https://ide.c9.io/ethanwilkins/anrcho
https://anrcho-ethanwilkins.c9users.io/

Should definitely have the IRC up by today as well.

**Comment by ethanwilkins** [comment]
Reopened because I still haven't set the channel up for IRC yet. I think I'm having issues connecting to freenode because of my ISP. Definitely feel free to set that up if you'd like though, especially if you'd like to be in charge of all that, I totally wouldn't mind.

**Comment by omouse** [comment]
Just created the channel on freenode, #anrcho is the name.

You may have to check your SSL or SASL settings and the port numbers. I had some weird issues around that a few times.

**Comment by ethanwilkins** [comment]
Awesome. Yeah, 'You need to identify via SASL to use this server (SASL access only)' is the error I'm getting. I do have tor installed and I'm using arch but I never explicitly set up tor for IRC, I might try uninstalling tor though. I just tried setting SASL options for nick and password to no avail.

**Comment by omouse** [comment]
@ethanwilkins here are the irc settings I have:

![freenode_irc_settings](https://cloud.githubusercontent.com/assets/2110497/12075910/3947e62c-b160-11e5-86fe-40143c9aadd4.png)

[There's also some info on freenode about SASL support](https://freenode.net/sasl/)

**Comment by ethanwilkins** [comment]
I was actually able to access the channel via https://webchat.freenode.net/
