### ISSUE TITLE
search engine optimization

### ISSUE THREAD

**Issue by omouse** [ethanwilkins/anrcho#5]
was reading about DemocracyOS which is a somewhat similar idea (less anonymous though and doesn't seem overly concerned about infosecurity), and they were found by a Tunisian activist through the Github search. They looked "constitution" and "voting platform" and I think the README and the description of the project should contain those keywords (along with any others that suggest democracy or voting).

**Comment by ethanwilkins** [comment]
Interesting, I added both keywords to the README but I'm not sure how I'm going to fit 'constitution' into the description but 'voting platform' should be easy enough. What do you think?

**Comment by omouse** [comment]
That makes sense to me and should be good enough.
